### ISSUE TITLE
"AS" bug in word prediction. 

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#106]
1. Load up the example Tree "Adult_Starter"
2. Navigate down to "I shall spell it". Select A, then select S.

You get 3 words - but they are all "as" - shouldnt one be "as" followed by words like "ask, asked" etc?

**Comment by hosseinamin** [comment]
This is because `trees/Spell_Prediction/bncfrequency.json` has three `"as"` within it.
I try to not add complexity to the prediction load. There's a check for sorting entries if they're not. Which will insure that prediction algorithm works.
It's not good to add more fixing within load process. It can slow down loading time.
I'm adding a PR with fixwords.js. Which does sort and remove duplicate.

**Comment by willwade** [comment]
Ah. Sorry. I thought I checked for duplicates. Clearly not. Sorry to bother you :)
