### ISSUE TITLE
Sliders too easy to change by accident when swiping down the page

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#139]
Re: #74 and #116 - the changes are great.. but now whats happening is that the sliders are getting changed when you swipe down the page. ? Change the action to only occur on horizontal movement??

**Comment by willwade** [comment]
Not urgent but I’ve been wondering if we should change the UI of config to something like https://framework7.io/ - it would solve our slider problem but also make it look more native

**Comment by gavinhenderson** [comment]
@willwade Gonna close this, because I can't replicate any issue with the sliders. 

The standard behaviour of sliders is that once you grab the slider you can move your finger anywhere on the screen and that will move the slider. I think it would be a lot of effort to go against this and would cause more unexpected. 

We could probably do with making sure the scroll targets are not in 'hot' zones for scrolling so they dont get activated on accident. However, I am going to close this issue as we will hopefully overhaul the settings design pages
