### ISSUE TITLE
Laggy and "Multiple Back" items on particular tree

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#176]
Load this: https://pastebin.com/raw/B3ciWjUd

and see the lag between loading second level items..

Video here: https://www.dropbox.com/s/si619ri8tcvzrwj/Untitled.mov?dl=0

**Comment by hosseinamin** [comment]
I've noticed the multiple back tree. I couldn't find a repeatable steps for replicating the issue. And There wasn't any obvious issue in the code.

About lagging issue I consider it normal in my view. But there are some in-ordinary operations are occurring to smooth transition at move event which are contributing to lagging. And that's because of styling. I used mostly css2 stylings at beginning. Upgrading to css3 can improve the performance. (Needs more thought)

**Comment by hosseinamin** [comment]
#180 can be a solution for this issue.
