### ISSUE TITLE
Prefix every item in branch with the same text

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#233]
I have a tree a bit like this..

```
			What is doing? (what is doing)
				Family
					What is Dad doing ?(dad)
					What is Mum doing ? (mum)
					What is Grandma and Grandad doing (grandparents)
					What is Grandma Dad’s mum doing? (Grandma dads)
					What is Matthew doing? (Matthew)
					What is Stephen doing? (Stephen)
					What is Lucy doing? (Lucy)
					What is Christopher doing? (Chris)
```

etc. This people chunk is used throughout but the action changes. 

What I think would be useful is if we could do a meta data-action-fill-gap "What is x doing" and in the next part of the tree it replaces x with the word. So it means we could do this:

```			
What is doing? (what is doing) -meta data-action-fill-gap main-message="What is x doing"-				
					Dad
					Mum
					Grandma and Grandad, mum’s parents
					Grandma Dad’s mum
					Matthew
					Stephen
					Lucy
					Christopher
```

Main message would then be "What is Dad doing" and cue would only be "Dad". Would be nice if this worked across other vocabulary trees. e.g. when we use change-tree-by-name

**Comment by gavinhenderson** [comment]
I like the idea but I feel like we should keep short hands like this out of the pasco vocab language itself and instead the pasco editor should make doing this easy. That way you can easily enter the format that you were describing but you can then edit

In general I prefer the idea of pushing complexity onto the editor rather than into the language.

@willwade Do you mind if I close this in favour of an issue to make the editor better?

**Comment by gavinhenderson** [comment]
Closing in favour of #288
