### ISSUE TITLE
Allow user configurable colour schemes

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#42]
We should allow users to configure colour schemes. This will allow users who are partially sighted to change the colours to whatever colour combination works for them best.

We should provide a set of base themes that are high contrast ([for example](http://tachyons.io/docs/themes/skins/)) but we should also allow users to fully configure the colours.

**Comment by gavinhenderson** [comment]
@willwade Since this issue was created we now have 'Themes'. We seems to have a pretty decent list of themes, do we ever encounter people who need something other than our provided themes? I suggest that for now, when that does happen we just add an extra base theme for that user manually. 

If thats alright with you will I will close this issue?
